# ==============================================================
# CARLA – Docker Build & Push Workflow
# Baut das Image automatisch und lädt es auf Docker Hub hoch.
# ==============================================================
name: Docker CI/CD

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login at Docker Hub
        uses: docker/login-action@v3
        with:
          username: l8tenever
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push CARLA
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            l8tenever/carla:latest
            l8tenever/carla:${{ github.sha }}
